# Generated by Django 5.2.6 on 2025-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время создания"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="время изменения"
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время создания"
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="время изменения"
            ),
        ),
    ]
